services:
  - type: web
    name: banknifty-futures-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18