services:
  - type: web
    name: banknifty-option-chain
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python start_services.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
      - key: PIP_PREFER_BINARY
        value: "true"